version: "3.7"

services:
    app:
      build: .
      working_dir: /app/sample
      tty: true
      ports:
        - 80:3000
      volumes:
        - ./:/app
      networks:
        - backend
      command: yarn dev

    mysql:
      image: mysql
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - ./data:/var/lib/mysql
      networks:
        - backend
      ports:
        - '3306:3306'
      environment:
        TZ: Asia/Tokyo
        MYSQL_ROOT_PASSWORD: app
        MYSQL_DATABASE: app
        MYSQL_USER: app
        MYSQL_PASSWORD: app

networks:
  backend:
